# Generated by Django 5.0.4 on 2024-04-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='AuditLocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='return_date',
        ),
    ]
