# Generated by Django 5.0.4 on 2024-04-29 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_name', '0002_rename_auditlocation_equipment_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 21, 41, 41, 533348, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
