# Generated by Django 5.0.4 on 2024-04-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_name', '0003_equipment_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.TextField(default='General purpose'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
