# Generated by Django 5.0.4 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_name', '0004_booking_duration_booking_end_date_booking_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
