# Generated by Django 5.0.4 on 2024-04-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_name', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
